### ISSUE TITLE
Repeated Warning on RMOT cooling limit

### ISSUE THREAD

**Issue by soeffi** [klaudiusz223/ComfoAirQ-Homie#1]
Hi,

in my logs, I'm seeing repeated messages like this:
`[homie.node.property.property_base]  [WARNING]  Invalid Value: Device ZehnderQ350 Node Controls Property Cooling Limit RMOT Value 16.0`

The corresponding value homie/zehnderq350/controls/cooling-rmot is reported incorrectly as 20.0 (ComfoControl App shows 16.0)

Any hints?

Anyway, thanks a lot for this great piece of software!
Stefan

**Comment by klaudiusz223** [comment]
Hi Stefan,
In my ComfoControl App (iOS) it is not possible  to set this value lower than 20 degrees, so I assumed that it cannot be lower.  It is limited in this line.  https://github.com/klaudiusz223/ComfoAirQ-Homie/blob/09ec1e01059361797c5f9a3d88889137d0b817a3/comfoairq_homie/homie_device/device_comfoairq.py#L320
Changing `data_format='20:40'` to e.g `data_format='10:40'` should fix this  problem.  Could You check if it works for You? 
Klaudiusz

**Comment by soeffi** [comment]
Yes, indeed, works for me with the extended range.

That was quick, thanks a lot!

**Comment by klaudiusz223** [comment]
OK. 
What is the minimum value for Your App?
Klaudiusz

**Comment by soeffi** [comment]
The Android App allows a range of 15-40°C.

Heating limit range is 0 - 15°C, so your choice with 0-20 should be ok.
