### ISSUE TITLE
Does not reconnect to MQTT after network failure

### ISSUE THREAD

**Issue by soeffi** [klaudiusz223/ComfoAirQ-Homie#2]
Hi,

after a network failure (e.g. router restart), I don't receive any further messages on the MQTT broker. After restarting the ComfoAirQ-Homie service, everything's fine.

Is there a chance to have the MQTT connection re-established with an automated retry function?

More information:

**When the network failure occurs, I get a lot of those messages:**
[homie.support.repeating_timer]  [ERROR]  Error in timer callback: Timeout waiting for response.  Traceback (most recent call last):
File "/home/soeffing/.local/lib/python3.7/site-packages/homie/support/repeating_timer.py", line 31, in _target
    callback()
  File "/home/soeffing/.local/lib/python3.7/site-packages/comfoairq_homie/homie_device/device_comfoairq.py", line 509, in update_heating_rmot
    reply_message = self.comfoairq.cmd_rmi_request(b'\x01\x1d\x01\x10\x02')
  File "/home/soeffing/.local/lib/python3.7/site-packages/comfoairq_homie/comfoairq/comfoairq.py", line 200, in cmd_rmi_request
    use_queue=use_queue
  File "/home/soeffing/.local/lib/python3.7/site-packages/pycomfoconnect/comfoconnect.py", line 228, in _command
    reply = self._get_reply(confirm_type, use_queue=use_queue)
  File "/home/soeffing/.local/lib/python3.7/site-packages/pycomfoconnect/comfoconnect.py", line 290, in _get_reply
    raise ValueError('Timeout waiting for response.')
ValueError: Timeout waiting for response.

**And the culprit**
[homie.device_base]  [INFO]  Device MQTT Connected state is False
[homie.mqtt.paho_mqtt_client]  [WARNING]  MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x7533acd0> None Connection refused - incorrect protocol version
[homie.mqtt.mqtt_base]  [WARNING]  MQTT On Disconnect: Result Code 1

**When the connection returns, I see this:**
[comfoconnect]  [INFO]  Unhandled CnNodeNotificationType
[comfoconnect]  [INFO]  Unhandled CnNodeNotificationType

**Comment by klaudiusz223** [comment]
Hi Stefan,
Which MQTT broker do you use? I did a test with mosquitto. I stopped mosquitto for couple of minutes (ComfoAirQ-Homie lost connection to broker) then started again and ComfoAirQ-Homie reconnect to broker after couple of minutes. I'm not sure I could do anything more in the near future to investigate it better.

**Comment by soeffi** [comment]
Hi Klaudiusz,

thanks for looking into that. I'm running mosquitto as well (on a different host). For some reason, after shutting down and restarting mosquitto, comfoairq_homie did not reconnect within 10 minutes.

Are you running mosquitto on the same host as your script? Not sure how that should make a difference, but I'm somewhat in the dark with that issue...

**Comment by soeffi** [comment]
Looking through the code, the error I see is probably just the connection timeout. Interestingly, it keeps emitting those messages for some time, until finally it throws a "Connection lost" message.

From what I understand, it will then try to reconnect for 3 times, as per these lines:
https://github.com/klaudiusz223/ComfoAirQ-Homie/blob/09ec1e01059361797c5f9a3d88889137d0b817a3/comfoairq_homie/comfoairq/comfoairq.py#L158-L160

I'll try whether increasing this number here will solve my problem, so that it keeps reconnecting basically forever.


Being curious: I'm not familiar with Python at all, maybe you can give me a hint: To make this max retry counter configurable, is it sufficient to use something like
`if _disconnection_counter > self.comfoconnect_settings['COMFOCONNECT_MAX_RETRY_CONNECT']:`
instead?

**Comment by klaudiusz223** [comment]
> Looking through the code, the error I see is probably just the connection timeout. Interestingly, it keeps emitting those messages for some time, until finally it throws a "Connection lost" message.
> 
> From what I understand, it will then try to reconnect for 3 times, as per these lines:
> https://github.com/klaudiusz223/ComfoAirQ-Homie/blob/09ec1e01059361797c5f9a3d88889137d0b817a3/comfoairq_homie/comfoairq/comfoairq.py#L158-L160
> 
> I'll try whether increasing this number here will solve my problem, so that it keeps reconnecting basically forever.
> 
> Being curious: I'm not familiar with Python at all, maybe you can give me a hint: To make this max retry counter configurable, is it sufficient to use something like
> `if _disconnection_counter > self.comfoconnect_settings['COMFOCONNECT_MAX_RETRY_CONNECT']:`
> instead?

**Comment by klaudiusz223** [comment]
Hi,
The code You quoted has nothing in common whit MQTT connection. This code is responsible for connection to Comfoconnect lan C bridge. Probably You don't find in my repository any code related to MQTT connection because I'm using Homie library and all the MQTT stuff  is done there.
But are You sure Your problems are related to MQTT?
The problems I faced for now are
- comfoconnec lan C bridge hangs from time to time (need bridge restart)
- If You use openhab 2.4 -  OH 2.4 has problems with Homie and if You lost You devices in OH ComfoAirQ-Homie restart is needed. It's probably fixed in OH >= 3

**Comment by klaudiusz223** [comment]
The problem also appeared for me after updating the bridge firmware to version U1.2.6. Should be fixed with bf1e456
